# Generated by Django 6.1.1 on 2026-09-24 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_land_area', models.DecimalField(decimal_places=2, help_text='In Hectares', max_digits=12)),
                ('acquired_land_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_land_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('compensation_status', models.CharField(default='Pending', max_length=50)),
                ('legal_dispute_status', models.CharField(default='No Disputes', max_length=50)),
                ('approval_status', models.CharField(default='Pending', max_length=50)),
                ('possession_status', models.CharField(default='Pending', max_length=50)),
                ('rehabilitation_status', models.CharField(default='Not Required', max_length=50)),
                ('project_status', models.CharField(choices=[('Planning', 'Planning'), ('Active', 'Active'), ('Delayed', 'Delayed'), ('Completed', 'Completed')], default='Planning', max_length=50)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_id', models.CharField(max_length=100, unique=True)),
                ('land_owner_count', models.IntegerField(default=0)),
                ('acquired_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('compensation_pending', models.BooleanField(default=True)),
                ('legal_cases', models.IntegerField(default=0)),
                ('possession_status', models.CharField(default='Pending', max_length=50)),
                ('rehabilitation_status', models.CharField(default='Pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_acquisitions', to='dashboard.project')),
            ],
        ),
    ]
