# Generated by Django 6.1.1 on 2026-09-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='Default Government API', max_length=100)),
                ('base_url', models.URLField(help_text='Base URL for the Government API')),
                ('api_key', models.CharField(help_text='API Key or Token for authentication', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Set to True to use this configuration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Government API Configuration',
                'verbose_name_plural': 'Government API Configurations',
            },
        ),
    ]
